apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/spring-boot-app:latest
          ports:
            - containerPort: 8080
